name: RELEASE

on:
  release:
    types:
      - 'published'

jobs:
  build:
    name: Build Watcher
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-15-intel, ubuntu-latest, windows-latest]
        node-version: [22.18.0]
        include:
          - os: macos-15-intel
            platform: macOS
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: Windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install --global npm@11.6.2
          npm ci

      - name: Build Application
        run: npm run release

      - name: MacOS/Linux Move and Rename Release file
        if: ${{ matrix.platform != 'Windows' }}
        run: |
          mv ./bin/index watcher-service-${{ github.event.release.tag_name }}-${{ matrix.platform }}

      - name: Windows Move and Rename Release file
        if: ${{ matrix.platform == 'Windows' }}
        run: |
          mv ./bin/index.exe watcher-service-${{ github.event.release.tag_name }}-${{ matrix.platform }}.exe

      - name: Upload File to Assets
        uses: softprops/action-gh-release@v2
        with:
          files: watcher-service-${{ github.event.release.tag_name }}-*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
